// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetCountURLs(ctx context.Context) (int64, error)
	GetCountURLsOfUser(ctx context.Context, userID int64) (int64, error)
	GetListURLs(ctx context.Context, arg GetListURLsParams) ([]GetListURLsRow, error)
	GetListURLsOfUser(ctx context.Context, arg GetListURLsOfUserParams) ([]GetListURLsOfUserRow, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUrlByLong(ctx context.Context, longUrl string) (Url, error)
	GetUrlByShort(ctx context.Context, shortUrl string) (Url, error)
	GetUser(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
