// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error)
	GetUrl(ctx context.Context, shortUrl string) (Url, error)
}

var _ Querier = (*Queries)(nil)
